#
# Troglobyte AppHub:
# author: Michael Gene Brockus
# gmail: <michaelbrockus@gmail.com>
#
name: Host Linux CI

#
# We have is configured so that ci_runner_linux only runs
# when source files, build scripts and this CI files is
# changed, we should not just run CI for all changes.
#
on:
  push:
    paths:
      - ".github/workflows/ci_runner_linux.yml"
      - "*.py"   # Python source files
  pull_request:
    branches:
      - "main"
      - "next"
    paths:
      - ".github/workflows/ci_runner_linux.yml"
      - "*.py"   # Python source files

permissions:
  contents: read

#
# We list all the Linux systems in a nice list so the
# DevOps team can manage them.
# 
jobs:
  #
  # Ubuntu host latest host system target
  #
  host_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build
      run: |
           sudo apt-get install --fix-missing python3 python3-pip -y &&
           python3 -m pip install pytest
    - name: Setup Troglo Project
      run: |
           python3 -m pip install -r requirements.txt
    - name: Scan Troglo Project
      run: |
           flake8 .
    - name: Test Troglo Project
      run: |
           python3 -m pytest test/run_tests.py

  #
  # Ubuntu host 22.04 host system target
  #
  host_ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build
      run: |
           sudo apt-get install --fix-missing python3 python3-pip -y &&
           python3 -m pip install pytest
    - name: Setup Troglo Project
      run: |
           python3 -m pip install -r requirements.txt
    - name: Scan Troglo Project
      run: |
           flake8 .
    - name: Test Troglo Project
      run: |
           python3 -m pytest test/run_tests.py

  #
  # Ubuntu host 20.04 host system target
  #
  host_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build
      run: |
           sudo apt-get install --fix-missing python3 python3-pip -y &&
           python3 -m pip install pytest
    - name: Setup Troglo Project
      run: |
           python3 -m pip install -r requirements.txt
    - name: Scan Troglo Project
      run: |
           flake8 .
    - name: Test Troglo Project
      run: |
           python3 -m pytest test/run_tests.py


  #
  # ChromeOS latest host system target
  #
  host_chromeos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nanasess/setup-chromedriver@v1.1.0
    - run: chromedriver --url-base=/wd/hub &
    - name: Install Meson build
      run: |
           sudo apt-get install --fix-missing python3 python3-pip -y &&
           python3 -m pip install pytest
    - name: Setup, Scan, Tests
      run: |
           python3 -m pip install -r requirements.txt
           flake8 .
           python3 -m pytest test/run_tests.py
